import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Geist ではなく Inter を使う
import "./globals.css";

// Google Fonts から Inter を読み込む設定
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Universe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body> のクラス名を inter.className に変える */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}